### ISSUE TITLE
Error if start is emitted

### ISSUE THREAD

**Issue by mcollina** [mcollina/avvio#3]
as titled. I think it's really a good idea, otherwise we cannot assume what's the current state.

cc @mcdonnelldean

**Comment by mcdonnelldean** [comment]
@mcollina Can you give me a code sample of what you mean?

**Comment by mcollina** [comment]
I mean, if you call `use` etc after we emit start, it's probably a bug.

**Comment by mcdonnelldean** [comment]
Oh, yes, I think so. If post load turns out to be a requirement I think it would need to be it's own queue anyway so let's restrict post load for now. (I'm not even sure it would work without weird side effects).

**Comment by mcollina** [comment]
@mcdonnelldean yes.

**Comment by mcollina** [comment]
This is fixed in #29
