### ISSUE TITLE
Support await for `after`  method

### ISSUE THREAD

**Issue by allevo** [mcollina/avvio#43]
Hi!
  currently the `ready` method support the promises. So you can write
```
await avvioInstance.ready()
console.log('UP!')
```

It can be useful for `after` method too.
```
await avvioInstance.use(...).after()
await Promise.all([
  avvioInstance.use(...).after(),
  avvioInstance.use(...).after()
])
...
await avvioInstance.ready()
console.log('UP!')
```

**Comment by mcollina** [comment]
Unfortunately that will not be feasible:

```js
avvio.use(async something (i, opts) {
  await this.after(func)
  // this line will never be executed
})
```

While `await avvio.ready()` make sense because it's top-level only.

BTW, there is no need to await on `.use()`.

**Comment by delvedor** [comment]
We already discussed about that in https://github.com/mcollina/avvio/pull/36.
You will run in a race condition, because `after` internally uses `use` :)
