### ISSUE TITLE
Change name to something less fun

### ISSUE THREAD

**Issue by mcdonnelldean** [mcollina/avvio#5]
Because of suits :D

**Comment by mcollina** [comment]
Suggestions?

**Comment by mcdonnelldean** [comment]
The one you already mentioned. I liked it.

**Comment by delvedor** [comment]
No please, I love this name 😂

**Comment by mcdonnelldean** [comment]
@delvedor Me too, not the wisest name when using to explain it to a professional or when doing a consultancy gig though.

**Comment by delvedor** [comment]
@mcdonnelldean I've to admit that your argument is pretty strong.
I'm gonna miss this name!

**Comment by mcollina** [comment]
Renamed to avvio.

**Comment by mcdonnelldean** [comment]
@mcollina Love it! It's perfect!
