### ISSUE TITLE
Inconsistent or not documented "close" interface

### ISSUE THREAD

**Issue by StarpTech** [mcollina/avvio#54]
First discussed [here](https://github.com/fastify/fastify/issues/867)

When the queue is [not empty](https://github.com/mcollina/avvio/blob/master/boot.js#L317) and a close handler was added the context is passed instead error.

In all cases of [close](https://github.com/mcollina/avvio#appclosefuncerror-context-done) the user expects an error.

**Comment by mcollina** [comment]
Definitely. 

Would you be able to send a PR?

**Comment by StarpTech** [comment]
What's your expectation?

**Comment by StarpTech** [comment]
I will prepare a PR

**Comment by StarpTech** [comment]
Released with https://github.com/mcollina/avvio/releases/tag/v5.4.2
