### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by HelloEdit** [mcollina/avvio#60]
Hello,

Is it planned to add TypeScript definitions to this module? I think it would be appreciated by the developers. I unfortunately do not have enough experience writing good definitions of my own.

Anyway, good work with avvio ^^

**Comment by mcollina** [comment]
Feel free to send a PR!

**Comment by HelloEdit** [comment]
Okay, I'll try, but if anyone else ever wants to contribute, feel free!

**Comment by HelloEdit** [comment]
Started on #61

**Comment by mcollina** [comment]
@HelloEdit I think this has been modelled in https://github.com/fastify/fastify/blob/master/fastify.d.ts#L310-L316
