### ISSUE TITLE
Invalid typescript interface for the Use method

### ISSUE THREAD

**Issue by Ethan-Arrowood** [mcollina/avvio#87]
I'm trying to use the `avvio.Use` interface (see below) in a `fastify` type def.

https://github.com/mcollina/avvio/blob/e2b5bd2d6e04c135249ac956e918c34a9a8aa731/index.d.ts#L67-L69

I don't understand how to invoke the `O` generic. Can someone either show me how to properly implement this interface or identify this as a bug so I we can fix it.

FWIW, I created a simpler version of it in TypeScript playground and I can't seem to reach that same generic value: [playground](https://www.typescriptlang.org/play/index.html#src=interface%20F%3CA%3E%20%7B%0D%0A%20%20%3CB%3E(foo%3A%20A%2C%20bar%3A%20B)%3A%20A%3B%0D%0A%7D%0D%0A%0D%0Aconst%20func%3A%20F%3Cstring%3E%20%3D%20(foo%2C%20bar)%20%3D%3E%20%7B%0D%0A%20%20return%20''%0D%0A%7D%0D%0A)

**Comment by mcollina** [comment]
I don’t think this is useful to expose in Fastify, as this is highly dynamic behavior that would be very hard to type. Essentially use() remaps to register() in Fastify.

Now, why all of this work is beyond my understanding.

**Comment by Ethan-Arrowood** [comment]
Yeah I've been messing with it for a while and still struggling to understand it (even opened a [SOF question](https://stackoverflow.com/questions/55604589/typescript-interface-function-type-with-generics/55604944#55604944))

I'll probably refrain from using it in the Fastify def and figure out another way to do it.
